/**
 * A self-contained backend for local development and the hermetic end-to-end tests: Postgres runs
 * in process (PGlite) and uploads are written to a folder instead of Vercel Blob. It keeps
 * `pnpm dev` and CI working without any Vercel credentials.
 *
 * Never enabled in a deployment: it is opt-in through ORIKATA_LOCAL_BACKEND.
 */
export const LOCAL_BACKEND_DIR = ".orikata-local";
export const LOCAL_BLOB_ROUTE = "/api/local-blob";

export function usingLocalBackend(): boolean {
  return process.env.ORIKATA_LOCAL_BACKEND === "1";
}

/** Whether a URL points at the local store rather than Vercel Blob. */
export function isLocalBlobUrl(url: string): boolean {
  try {
    return new URL(url).pathname.startsWith(`${LOCAL_BLOB_ROUTE}/`);
  } catch {
    return false;
  }
}

/** The file name a local blob URL refers to, or null if the URL is not one of ours. */
export function localBlobName(url: string): string | null {
  if (!isLocalBlobUrl(url)) return null;
  const name = new URL(url).pathname.slice(`${LOCAL_BLOB_ROUTE}/`.length);
  // Names are generated by the upload route, but never trust one that came back from a client.
  return /^[0-9a-f]{32}\.fold$/.test(name) ? name : null;
}
