/**
 * Runs both animation prototypes over every transition of every valid fixture and writes
 * `reports/animation-comparison.md`. Run with `pnpm compare`.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { LerpAnimator } from "@/animation/lerp";
import {
  measureTransition,
  SAMPLE_DT,
  subdivide,
  type TransitionMetrics,
} from "@/animation/metrics";
import { SolverAnimator } from "@/animation/solver/animator";
import { buildSolverModel } from "@/animation/solver/model";
import { loadFold, type ResolvedModel } from "@/fold";
import type { FoldAnimator } from "@/animation/types";

const FIXTURES = ["book-fold", "book-fold-90", "diagonal-twice", "preliminary-base"] as const;

const ANIMATORS: { name: string; create: () => FoldAnimator }[] = [
  { name: "A · lerp", create: () => new LerpAnimator() },
  { name: "B · solver", create: () => new SolverAnimator() },
];

interface Row {
  fixture: string;
  label: string;
  animator: string;
  metrics: TransitionMetrics;
}

function loadFixture(name: string): ResolvedModel {
  const text = readFileSync(join(process.cwd(), "fixtures", "valid", `${name}.fold`), "utf8");
  const result = loadFold(text);
  if (!result.ok) throw new Error(`${name}: ${result.errors[0]?.message}`);
  return result.model;
}

function percent(value: number): string {
  return `${(value * 100).toFixed(2)}%`;
}

function main(): void {
  const rows: Row[] = [];
  for (const fixture of FIXTURES) {
    const model = loadFixture(fixture);
    for (let to = 1; to < model.frames.length; to++) {
      for (const animator of ANIMATORS) {
        rows.push({
          fixture,
          label: `${to - 1}→${to}`,
          animator: animator.name,
          metrics: measureTransition(model, animator.create(), to - 1, to),
        });
      }
    }
  }

  const scaling: string[] = [];
  let model = loadFixture("preliminary-base");
  for (const level of [0, 1, 2, 3, 4, 5]) {
    if (level > 0) model = subdivide(model);
    const solverModel = buildSolverModel(model);
    const cells = ANIMATORS.map((animator) => {
      const metrics = measureTransition(model, animator.create(), 2, 3);
      return `${metrics.msPerFrame.toFixed(2)} ms`;
    });
    scaling.push(
      `| ×${4 ** level} | ${model.vertexCount} | ${solverModel.axial.length} | ${solverModel.hinges.length} | ${cells.join(" | ")} |`,
    );
  }

  const lines: string[] = [
    "# Animation prototype comparison",
    "",
    `Generated by \`pnpm compare\` on ${new Date().toISOString().slice(0, 10)}.`,
    "",
    "Distortion is measured against the flat sheet in frame 0: edge strain is the relative change",
    "in a model edge's length, angle strain the absolute change in a face's interior angle. Samples",
    "are taken every rendered frame at a fixed 60 fps, for the whole transition including the",
    "landing. `landed` is whether the animator finished exactly on the author's stored geometry.",
    "",
    "## Distortion and cost per transition",
    "",
    "| Fixture | Step | Animator | Max edge strain | Mean edge strain | Max angle strain | Landed | ms/frame |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
  ];
  for (const row of rows) {
    lines.push(
      `| ${row.fixture} | ${row.label} | ${row.animator} | ${percent(row.metrics.maxEdgeStrain)} | ${percent(row.metrics.meanEdgeStrain)} | ${row.metrics.maxAngleStrainDeg.toFixed(2)}° | ${row.metrics.landed ? "yes" : "**no**"} | ${row.metrics.msPerFrame.toFixed(3)} |`,
    );
  }

  lines.push("", "## What the solver's landing costs", "");
  lines.push(
    "Residuals are the worst crease's distance from its target: at the end of the tween, and again",
    "when the solver stops settling and hands over. The landing distance is how far any vertex still",
    "has to move during the 150 ms blend onto the author's geometry, in model units.",
    "",
    "| Fixture | Step | Residual at tween end | Residual at handover | Settle frames | Landing distance |",
    "| --- | --- | --- | --- | --- | --- |",
  );
  for (const fixture of FIXTURES) {
    const source = loadFixture(fixture);
    const span = Math.max(...source.frames.flatMap((frame) => Array.from(frame.coords, Math.abs)));
    for (let to = 1; to < source.frames.length; to++) {
      const animator = new SolverAnimator();
      measureTransition(source, animator, to - 1, to);
      const d = animator.lastTransition();
      lines.push(
        `| ${fixture} | ${to - 1}→${to} | ${d.residualAtTweenEndDeg.toFixed(2)}° | ${d.residualAtLandingDeg.toFixed(2)}° | ${d.settleFrames} | ${d.landingDistance.toFixed(4)} (${((d.landingDistance / span) * 100).toFixed(2)}% of the model) |`,
      );
    }
  }

  lines.push(
    "",
    "## Scaling, on preliminary-base 2→3 subdivided",
    "",
    "Each level splits every face into four. Times are this machine's; see the report body for what",
    "they mean on slower hardware.",
    "",
    `| Subdivision | Vertices | Axial springs | Hinges | ${ANIMATORS.map((a) => a.name).join(" | ")} |`,
    `| --- | --- | --- | --- | ${ANIMATORS.map(() => "---").join(" | ")} |`,
    ...scaling,
    "",
  );

  for (const fixture of FIXTURES) {
    const source = loadFixture(fixture);
    for (let to = 1; to < source.frames.length; to++) {
      writeContactSheet(fixture, source, to - 1, to);
    }
  }

  const path = join(process.cwd(), "reports", "animation-metrics.md");
  writeFileSync(path, lines.join("\n"));
  process.stdout.write(`wrote ${path}\n`);
}

/** Samples of the transition timeline captured for the contact sheets. */
const SAMPLE_POINTS = [0, 0.25, 0.5, 0.75, 1];
const TILE = 190;
const HEADER = 20;
const PAPER_FRONT = "#efe8d8";
const PAPER_BACK = "#e0b36a";

/**
 * Renders the same transition under both animators as one SVG, five samples across. Drawing the
 * geometry directly rather than screenshotting the viewer keeps the figures reproducible: the same
 * fixed timestep produces the same picture every run.
 */
function writeContactSheet(fixture: string, model: ResolvedModel, from: number, to: number): void {
  const rows = ANIMATORS.map((animator) => ({
    name: animator.name,
    shapes: sampleTransition(model, animator.create(), from, to),
  }));
  // One view for every tile, taken from what is actually drawn, so the two rows are comparable.
  const view = fitView(rows.flatMap((row) => row.shapes));

  const width = TILE * SAMPLE_POINTS.length;
  const height = HEADER + rows.length * (TILE + HEADER);
  const parts: string[] = [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" font-family="system-ui, sans-serif">`,
    `<rect width="${width}" height="${height}" fill="#fbfbfa"/>`,
  ];
  SAMPLE_POINTS.forEach((point, c) => {
    parts.push(
      `<text x="${c * TILE + TILE / 2}" y="14" font-size="11" fill="#888" text-anchor="middle">${Math.round(point * 100)}%</text>`,
    );
  });
  rows.forEach((row, r) => {
    const top = HEADER + r * (TILE + HEADER);
    parts.push(
      `<text x="8" y="${top + 13}" font-size="12" fill="#444">${escapeXml(row.name)}</text>`,
    );
    row.shapes.forEach((coords, c) => {
      parts.push(
        `<g transform="translate(${c * TILE}, ${top + HEADER})">`,
        drawModel(model, coords, view, to),
        "</g>",
      );
    });
  });
  parts.push("</svg>");

  const dir = join(process.cwd(), "reports", "figures");
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, `${fixture}-${from}-${to}.svg`), parts.join("\n"));
}

/** Runs a transition at a fixed timestep and keeps the geometry at each sample point. */
function sampleTransition(
  model: ResolvedModel,
  animator: FoldAnimator,
  from: number,
  to: number,
): Float32Array[] {
  const positions = new Float32Array(model.vertexCount * 3);
  animator.init(model, positions);
  animator.jumpTo(from);

  const trace: Float32Array[] = [Float32Array.from(positions)];
  animator.beginTransition(from, to);
  for (let i = 0; i < 600; i++) {
    const state = animator.step(SAMPLE_DT);
    trace.push(Float32Array.from(positions));
    if (state === "idle") break;
  }
  animator.dispose();
  return SAMPLE_POINTS.map((s) => trace[Math.round(s * (trace.length - 1))]!);
}

interface View {
  scale: number;
  cx: number;
  cy: number;
}

/** A fixed three-quarter view, the same for every tile, with z up the page. */
function project(coords: ArrayLike<number>, v: number): [number, number, number] {
  const x = coords[3 * v]!;
  const y = coords[3 * v + 1]!;
  const z = coords[3 * v + 2]!;
  const cos = Math.cos(Math.PI / 6);
  const sin = Math.sin(Math.PI / 6);
  return [(x - y) * cos, (x + y) * sin - z, x + y + 2 * z];
}

function fitView(shapes: Float32Array[]): View {
  let minX = Infinity;
  let maxX = -Infinity;
  let minY = Infinity;
  let maxY = -Infinity;
  for (const coords of shapes) {
    for (let v = 0; v < coords.length / 3; v++) {
      const [x, y] = project(coords, v);
      minX = Math.min(minX, x);
      maxX = Math.max(maxX, x);
      minY = Math.min(minY, y);
      maxY = Math.max(maxY, y);
    }
  }
  const span = Math.max(maxX - minX, maxY - minY, 1e-6);
  return { scale: (TILE * 0.82) / span, cx: (minX + maxX) / 2, cy: (minY + maxY) / 2 };
}

function drawModel(
  model: ResolvedModel,
  coords: Float32Array,
  view: View,
  assignmentFrame: number,
): string {
  const place = (v: number): [number, number, number] => {
    const [x, y, depth] = project(coords, v);
    return [TILE / 2 + (x - view.cx) * view.scale, TILE / 2 + (y - view.cy) * view.scale, depth];
  };

  // Painter's algorithm: draw the far faces first, and colour the side of the paper facing us.
  const faces = model.facesVertices
    .map((face) => {
      const points = face.map(place);
      return {
        points,
        depth: points.reduce((sum, p) => sum + p[2], 0) / points.length,
        fill: signedArea(points) > 0 ? PAPER_FRONT : PAPER_BACK,
      };
    })
    .sort((a, b) => b.depth - a.depth);

  const parts = faces.map(
    ({ points, fill }) =>
      `<polygon points="${points.map((p) => `${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(" ")}" fill="${fill}" stroke="#8d8d8d" stroke-width="0.5"/>`,
  );

  const assignments = model.frames[assignmentFrame]!.assignments;
  model.edgesVertices.forEach(([a, b], e) => {
    const assignment = assignments[e];
    if (assignment !== "M" && assignment !== "V") return;
    const [x1, y1] = place(a);
    const [x2, y2] = place(b);
    parts.push(
      `<line x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}" stroke="${assignment === "M" ? "#d2262c" : "#1f5fd0"}" stroke-width="1.6"/>`,
    );
  });

  return parts.join("");
}

function signedArea(points: [number, number, number][]): number {
  let area = 0;
  for (let i = 0; i < points.length; i++) {
    const p = points[i]!;
    const q = points[(i + 1) % points.length]!;
    area += p[0] * q[1] - q[0] * p[1];
  }
  return area / 2;
}

function escapeXml(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

main();
